name: Bandit checks

on: [push]

jobs:
  unittests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Setup poetry
        run: pip install poetry

      - name: Install poetry
        run: poetry install

      - name: Perform bandit test
        run: poetry run bandit -r ./api ./database ./innotasks ./repository
