name: Check coverage

on: [push]

jobs:
  unittests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Setup poetry
        run: pip install poetry

      - name: Install poetry
        run: poetry install

      - name: Install pytest and mock
        run: poetry add pytest pytest-mock pytest-cov

      - name: Do combined coverage
        run: poetry run pytest --cov=innotasks --cov=api --cov=database --cov=repository --cov-branch --cov-report=term --cov-fail-under=60
