name: CI/CD

on: [push]

jobs:
  linter:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black

    - name: Format code with Black
      run: |
        black .

    - uses: stefanzweifel/git-auto-commit-action@v5

    - name: Lint code
      run: |
        flake8 --ignore=E501  .

  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Setup poetry
        run: pip install poetry

      - name: Install poetry
        run: poetry install

      - name: Perform bandit test
        run: poetry run bandit -r ./api ./database ./repository

  tests:
    needs: security
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Setup poetry
        run: pip install poetry

      - name: Install poetry
        run: poetry install

      - name: Do combined coverage
        run: poetry run pytest --cov=innotasks --cov=api --cov=database --cov=repository --cov-branch --cov-report=term --cov-fail-under=60
